service: recommendationendpointintegration

provider:
  name: aws
  runtime: python3.7
  iamRoleStatements:
    - Effect: 'Allow'        
      Action: 's3:*' 
      Resource: '*'
    - Effect: 'Allow'        
      Action: 'sagemaker:Invoke*' 
      Resource: '*'
functions:
  hello:
    handler: handler.handler
    events:
      - http:
          path: recommendEndpoint
          method: get
    # As we want to use ndArray include the public data science layer from AWS which includes numpy library
    layers:
      - arn:aws:lambda:us-east-1:668099181075:layer:AWSLambda-Python37-SciPy1x:2
    # EDIT BELOW LINES
    # Example:
    # EMBEDDINGS_S3_PATH: s3://sagemaker-us-east-1-xxxxxxxx/fm/output/factorization-machines-2019-11-07-20-37-16-285/output/user_embeddings.pickle
    # SAGEMAKER_ENDPOINT_NAME: knn-2019-10-24-19-35-08-799
    environment:
      EMBEDDINGS_S3_PATH: s3://your-bucket-url/fm/output/factorization-machines-2019-10-24-19-30-22-215/output/user_embeddings.pickle
      SAGEMAKER_ENDPOINT_NAME: <your-endpoint-name>
